### ISSUE TITLE
Context menu should open to the left if opening source is on the mostfar right 

### ISSUE THREAD

**Issue by azaberlin** [vaadin/vaadin-context-menu#143] opened 2018-03-13 12:56 UTC
I added a button to my template, that should open a context menu when clicked like in this example: https://vaadin.com/#context-menu-advanced-demos.

The button is in the upper right corner, right beside the window border. When I click the button, the context menu opens, but tries to open to the right and is squeezed through that.

![image](https://user-images.githubusercontent.com/26115592/37342846-7b78c1ca-26ce-11e8-9f80-385243c8bcbe.png)

I would expect it to be in normal width and open to the left.

**Comment by jouni** [comment] 2018-03-13 13:07
I consider this as a duplicate of #115

**Closed by jouni** 2018-03-13 13:07 UTC
