### ISSUE TITLE
Disable scrolling when context menu is shown

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-context-menu#67] opened 2017-02-07 07:21 UTC
In Windows scroll event is closing context menu and then scrolls document.
In Linux and macOS scrolling is disabled while context menu is opened.

We decided to go Linux/macOS way and disable window scrolling when context menu is shown.

**Comment by tomivirkki** [comment] 2017-10-04 08:06
Disabling window scrolling would result in jumpy behaviour (when the scrollbars disappear/re-appear) on environments where the scrollbars are visible by default. I see the current approach nicer. We could consider making the overlay adapt to window scroll position, kind of like what combo box overlay does now.

**Comment by limonte** [comment] 2017-10-04 08:08
> Disabling window scrolling would result in jumpy behaviour (when the scrollbars disappear/re-appear) on environments where the scrollbars are visible by default. 

Not necessarily: https://stackoverflow.com/a/4770179/1331425

**Comment by tomivirkki** [comment] 2017-10-04 08:27
That approach can get tricky since you can place any scrollable content inside the context menu. I recall us prototyping this before but might be worth revisiting.

**Comment by limonte** [comment] 2017-10-04 08:32
> That approach can get tricky since you can place any scrollable content inside the context menu.

Yeah, the famous grid-inside use case :D

**Comment by tomivirkki** [comment] 2017-10-04 08:33
Or a paper-menu like in all of our examples :D

**Comment by tomivirkki** [comment] 2017-10-04 08:40
This is actually a duplicate of https://github.com/vaadin/vaadin-context-menu/issues/39 Closing.

**Closed by tomivirkki** 2017-10-04 08:40 UTC
